### ISSUE TITLE
When can you open source?

### ISSUE THREAD

**Issue by qhdqhd** [json87/SphereSfM#1]
Thanks for your great work!

**Comment by json87** [comment]
The related manuscript is under peer review. After that, I would release the code. You can refer to the following preprint.

https://arxiv.org/abs/2306.12770

**Comment by nofreewill42** [comment]
Hello there, thanks for your research and hard work, appreciated! : )
Why is it required not to be under peer review for releasing the code?

**Comment by nofreewill42** [comment]
Ah, nice ! Thank you so much! : ))
