### ISSUE TITLE
  No good initial image pair found.

### ISSUE THREAD

**Issue by Luffy2810** [json87/SphereSfM#10]
I am trying to create a sparse reconstruction using the code provided on campus building dataset. I have followed the exact steps given in the repo but after running the matcher, I am encountering this error:   => No good initial image pair found.

**Comment by json87** [comment]
I think you should decrease the distance between frames during data collection.

**Comment by Luffy2810** [comment]
I am using the dataset provided by you in the google drive, the campus building dataset. Is it possible I need to change values of some hyper-parameters or something?

**Comment by json87** [comment]
You can use both spatial and sequential feature matching to increase the number of matched image pairs.

**Comment by Luffy2810** [comment]
I tried using VocabMatcher, SpatialMatcher and Sequential Matcher smae issue persists.
Here is the code with all the hyperparameters am using:

~~~
# #!/bin/bash


colmap database_creator --database_path ./database.db


colmap feature_extractor \
--database_path ./database.db \
--image_path ./images \
--ImageReader.camera_model SPHERE \
--ImageReader.camera_params "1,5640,2820" \
--ImageReader.single_camera 1 


# colmap spatial_matcher \
# --database_path ./database.db \
# --SiftMatching.max_error 4 \
# --SiftMatching.min_num_inliers 50 \
# --SpatialMatching.is_gps 0 \
# --SpatialMatching.max_distance 50
# --SpatialMatching.vocab_tree_path ../vocab_tree_flickr100K_words256K.bin

colmap sequential_matcher \
--database_path ./database.db \
--SiftMatching.max_error 4 \
--SiftMatching.min_num_inliers 50 \
--SiftMatching.max_num_matches 11000
# --SequentialMatching.is_gps 0 \
--SequentialMatching.max_distance 50\
--SequentialMatching.vocab_tree_path ../vocab_tree_flickr100K_words256K.bin

# colmap vocab_tree_matcher \
#     --database_path ./database.db \
#     --VocabTreeMatching.vocab_tree_path ../vocab_tree_flickr100K_words256K.bin

    
mkdir sparse
colmap mapper \
--database_path ./database.db \
--image_path ./images \
--output_path ./sparse \
--Mapper.ba_refine_focal_length 0 \
--Mapper.ba_refine_principal_point 0 \
--Mapper.ba_refine_extra_params 0 \
--Mapper.sphere_camera 1


~~~

**Comment by json87** [comment]
For spatial matching, --SpatialMatching.is_gps is set as 1 because the position data is from GNSS in the lon-lat-alt format.
