### ISSUE TITLE
Integration with the official COLMAP codebase? 

### ISSUE THREAD

**Issue by rigolepe** [json87/SphereSfM#12]
Great work! I really believe 360 cameras are an ideal way to cope with the limitations of pure forward-motion recordings with a single camera. 

If I understand it correctly, the SphereSfM code was initiated from a COLMAP copy at some point in time. This automatically means that it will diverge over time from the official COLMAP codebase. 

Is there a roadmap to provide a pull request that integrates the SphereSfM changes into the official COLMAP repository?

**Comment by json87** [comment]
As pointed out by you, the code in this repo is based on the tag version 3.8 of COLMAP. It is a good idea to merge the code into the official COLMAP repo. However, I do not have enough time right now. In addition, the code structure of COLMAP has extremely large changes for the latest version, and I cannot ensure the success of code merging.
