### ISSUE TITLE
Issue while merging the model

### ISSUE THREAD

**Issue by paidiakileswar** [json87/SphereSfM#13]
![image](https://github.com/json87/SphereSfM/assets/155959310/6f2226bd-8af2-48fc-a57e-24edbf2a39c8)

**Comment by json87** [comment]
There are not enough common images between these two recons. In the merge tool, three at least common images are required.

**Comment by paidiakileswar** [comment]
I ran a dataset with 800 images , how can i get overlap of minimum 3 images for every each sparse !

I ran step wise
Feature Extractor , Spatial Matcher , Mapper , Model Aligner

Any idea or suggestion will be helpful @json87 

Regards 
Akileswar

**Comment by json87** [comment]
Split the dataset into two subsets with at least three common images and reconstruct them individually.

**Comment by paidiakileswar** [comment]
So i get two different sparse outputs like

1st dataset
sparse - 0

2nd dataset
sparse - 0

So i should give these paths to model merger right !!
