### ISSUE TITLE
Issue Regarding POS.txt in SphereSFM

### ISSUE THREAD

**Issue by paidiakileswar** [json87/SphereSfM#14]
So we have 

POS.txt 
in the format `x,y,z,R_ARRAY
`

But i have geo.txt which have
### **x,y,z which are UTM Coordinates**

Should i have to consider here
`UTM(X,Y,Z) `Coordinates converted to` LAT,LONG,ALT in POS.txt` or should i consider directly while using the 

Spatial Matcher command
`--ImageReader.pose_path ./POS.txt`

**Comment by json87** [comment]
For UTM coordinates, just set --SpatialMatching.is_gps 0

**Comment by paidiakileswar** [comment]
Got it Thanks 🙂
