### ISSUE TITLE
Issue in Reconstruction in Dark & White Walls cases

### ISSUE THREAD

**Issue by paidiakileswar** [json87/SphereSfM#15]
Hai @json87 

So My dataset is of full dark places and contains full of white walls where usually there is no features at that place but still there will some features like doors and some other objects ! 

So in this case i considered number of features to 100,000 and considering SIFT disp and changed some params !! Even though spatial,Exhaustive,Sequential Matching failed here !!

When considering maximum resolution 6720*3360 , Even though features and matches got increased the reconstruction is not forming well !!

So please can you suggest me some ideas or suggestions how can i finally get good sparse in these cases?? 

Best Regards
Akileswar

**Comment by paidiakileswar** [comment]
@satyajitghana Can you help me with this !!

Best Regards
Akileswar

**Comment by json87** [comment]
I think two issues you should pay attention to. First, images should be collected with high overlap degrees and large intersection angles. Second, for textureless regions, the default SIFT algorithm could be fail. I think the learned feature matching mehod could be an alternative, such as LoFTR and AspanFormer.

**Comment by paidiakileswar** [comment]
Got it , Thanks very much @json87 ☺️
