### ISSUE TITLE
When using BOW, the code crashes

### ISSUE THREAD

**Issue by chenxianbo** [json87/SphereSfM#16]
cuda: 11.3
cmake: 3.36.0
Defects as title

**Comment by json87** [comment]
Please give the details.

**Comment by chenxianbo** [comment]
terminate called after throwing an instance of 'flann::FLANNException'
  what():  Invalid index file, wrong signature
*** Aborted at 1717552088 (unix time) try "date -d @1717552088" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x3e800004d64) received by PID 19812 (TID 0x7fd465388700) from PID 19812; stack trace: ***
    @     0x7fd4ad472390 (unknown)
    @     0x7fd4a8de9438 gsignal
    @     0x7fd4a8deb03a abort
    @     0x7fd4a95253df __gnu_cxx::__verbose_terminate_handler()
    @     0x7fd4a9523b16 __cxxabiv1::__terminate()
    @     0x7fd4a9523b4c std::terminate()
    @     0x7fd4a9523d28 __cxa_throw
    @           0x4da7bd flann::NNIndex<>::serialize<>()
    @           0x4da981 flann::AutotunedIndex<>::serialize<>()
    @           0x4dabf4 flann::AutotunedIndex<>::loadIndex()
    @           0x4db2ad colmap::retrieval::VisualIndex<>::Read()
    @           0x5a9a1f colmap::VocabTreeFeatureMatcher::Run()
    @           0x6ef3fc colmap::Thread::RunFunc()
    @     0x7fd4a953f678 execute_native_thread_routine_compat
    @     0x7fd4ad4686ba start_thread
    @     0x7fd4a8ebb51d clone
    @                0x0 (unknown)

**Comment by json87** [comment]
Refering to the code "colmap::retrieval::VisualIndex<>::Read()", I think the issue arises from the used vocabulary tree.

**Comment by chenxianbo** [comment]
it is ok for official colmap to use the vocabulary (vocab_tree_flickr100K_words1M.bin).

**Comment by chenxianbo** [comment]
I solve the problem，the linked FLANN library is incompatible
