### ISSUE TITLE
Issue While Mergin the model

### ISSUE THREAD

**Issue by zhangChen341** [json87/SphereSfM#18]
Hai @json87 

This is a great Work

So can you help me with this

While I am trying model merger 
I had got this issue

![image](https://github.com/json87/SphereSfM/assets/167770941/1c30b198-948c-48f8-8439-7958ad84cdea)

So i used command as this
`
colmap model_merger \
                                     --input_path1 0 \
                                     --input_path2 1 \
                                     --output_path merged \
                                     --max_reproj_error 100
`

I have 0,1 with images.bin,cameras.bin,points3d.bin and merged folder created before only

I have sufficient overlap 

split_ranges = [
    (0, 400),    
    (300, 700),  
    (600, 1000),
    (900, 1217)  
]

I have here used a single database as per Issue : https://github.com/colmap/colmap/issues/1703#issuecomment-1331828759

Maintained a single database during mapper i have done giving list.txt with image names

UNIQUE IMAGE IDS
![image](https://github.com/json87/SphereSfM/assets/167770941/662f3b6c-c9e3-467b-9e07-07c3f60bc907)

Can you please tell me with Is this problem with SphereSFM

**Comment by json87** [comment]
I have not test model merge for spherical images, If possible, you can share these two models for test.
