### ISSUE TITLE
Issue With Model Merger in SphereSFM

### ISSUE THREAD

**Issue by paidiakileswar** [json87/SphereSfM#19]
Hai @json87 @satyajitghana 

I was trying to merge my 2 models

## **Method - 1:**

So Firstly i divided my images

SPLIT 1 => 1- 400
SPLIT 2 => 300 - 700

Here i got 2 sparses as output from both SPLIT 1 and SPLIT 2 , Both of them i reconstucted in differently , (like in 2 servers )

So i have now scaled outputs of SPLIT 1 & SPLIT 2 which i have got after applying mapper & model aligner

Now 
I have 2 sparses i converted them into .txt files

So i have 
sparse_1 -> cameras.txt,images.txt,points3D.txt

sparse_2 -> cameras.txt,images.txt,points3D.txt

I have modified the image_id in both images.txt & points3D.txt , such that they are unique as per https://github.com/colmap/colmap/issues/1703#issuecomment-1331828759

![Screenshot 2024-06-25 142533](https://github.com/colmap/colmap/assets/155959310/d9924cee-b6cf-45dc-a3d5-e95814b7a07d)

I am getting this issue , Please help me here

## **Method - 2:**

Here i have 438 images

I divided as
1 - 250
200 - 438

So i done Feature Extraction , Matching , 

Mapper here i changed the 
using
--image_list_path names_1.txt 
--image_list_path names_2.txt 

I got 2 sparses

While merging 
`colmap model_merger --input_path1 ./sparse/0/ --input_path2 ./sparse_1/0/ --output_path ./merger/ `

I got this issue

![image](https://github.com/colmap/colmap/assets/155959310/839ad4e7-8a3d-46a1-9982-f5ea80d14549)

Stack Backtrace

![image](https://github.com/colmap/colmap/assets/155959310/a18a5d98-bf84-470e-b4c2-52cc3788eebd)

Could you help me here , I am stuck here
Best Regards
Akil

**Comment by satyajitghana** [comment]
Hi,

how can I reproduce your output?

can you share some example datasets? and the commands you used? you can share me a google drive link.

**Comment by paidiakileswar** [comment]
Here is the sample data i used @satyajitghana 

Link : https://drive.google.com/drive/folders/16sKJOZrbJTvSf3g4eZtk2wKkLtwXA0hx?usp=sharing

My folder structure
```
-images
------------VID_....JPG
------------VID_....JPG
------------VID_....JPG

-POS.txt

-colmap
-------------database.db
-------------sparse
-------------sparse_1
```

Commands:

1)
`colmap database_creator --database_path ./colmap/database.db`

2)
`time colmap feature_extractor     --database_path ./colmap/database.db     --image_path ./images     --ImageReader.camera_model SPHERE     --ImageReader.camera_params "1,2048,1024"     --ImageReader.single_camera 1     --ImageReader.pose_path ./POS.txt`
 
 3)
`time colmap spatial_matcher     --database_path ./colmap/database.db     --SiftMatching.max_error 4     --SiftMatching.min_num_inliers 50     --SpatialMatching.is_gps 0     --SpatialMatching.max_distance 50`

4)
`time colmap mapper     --database_path ./colmap/database.db     --image_path ./images     --output_path ./colmap/sparse     --Mapper.ba_refine_focal_length 0     --Mapper.ba_refine_principal_point 0     --Mapper.ba_refine_extra_params 0     --Mapper.sphere_camera 1     --image_list_path names_1.txt`

5)
` time colmap mapper     --database_path ./colmap/database.db     --image_path ./images     --output_path ./colmap/sparse_1     --Mapper.ba_refine_focal_length 0     --Mapper.ba_refine_principal_point 0     --Mapper.ba_refine_extra_params 0     --Mapper.sphere_camera 1     --image_list_path names_2.txt`
 
 I got two sparses as output 
 1 in sparse/0
 2 in sparse_1/0
 
 Then i created `mkdir merger`
 and ran the command
 
 `colmap model_merger --input_path1 ./colmap/sparse/0/ --input_path2 ./colmap/sparse_1/0/ --output_path ./merger/`
 
 Hope this data is sufficient , Please help me with this @satyajitghana

**Comment by satyajitghana** [comment]
@paidiakileswar how was the POS.txt generated?

**Comment by paidiakileswar** [comment]
@satyajitghana 

POS.txt contains

#F=N X Y Z R

Name and x,y,z utm coordinates and R array i considered as identity matrix

`
[1 0 0
0 1 0
0 0 1]
`

I have name x,y,z from camera geo positions then i added identity matrix at the end to every row that it! 

In this way i generated POS.txt , it worked fine on all the datasets !

**Comment by satyajitghana** [comment]
ok, let me try it out tomorrow

**Comment by paidiakileswar** [comment]
Thanks very much @satyajitghana 

My aim is to get good sparse here and use it further densification , if any suggestions or methods other than this - you can suggest me that will be helpful to my research so much !!

Best Regards
Paidi Akileswar

**Comment by satyajitghana** [comment]
```
F20240628 12:26:56.631281 3829852 mat.h:167] Check failed: width_ > 0 (0 vs. 0) 
*** Check failure stack trace: ***
    @     0x7f5e2c31403e  google::LogMessage::Fail()
    @     0x7f5e2c313f80  google::LogMessage::SendToLog()
    @     0x7f5e2c31379e  google::LogMessage::Flush()
    @     0x7f5e2c317442  google::LogMessageFatal::~LogMessageFatal()
    @     0x5638fe25df63  colmap::mvs::Mat<>::Read()
    @     0x5638fe25c3c9  colmap::mvs::CachedWorkspace::GetDepthMap()
    @     0x5638fe4f705d  colmap::mvs::PatchMatchController::ProcessProblem()
    @     0x5638fe4fac3d  _ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultIvEES3_EZNS1_11_Task_stateISt5_BindIFMN6colmap3mvs20PatchMatchControllerEFvRKNSD_17PatchMatchOptionsEmEPSE_SF_mEESaIiEFvvEE6_M_runEvEUlvE_vEEE9_M_invokeERKSt9_Any_data
    @     0x5638fe081f8d  std::__future_base::_State_baseV2::_M_do_set()
    @     0x7f5e0140a4df  __pthread_once_slow
    @     0x5638fe4fb491  _ZNSt17_Function_handlerIFvvEZN6colmap10ThreadPool7AddTaskIMNS1_3mvs20PatchMatchControllerEFvRKNS4_17PatchMatchOptionsEmEJPS5_S8_RmEEESt6futureINSt9result_ofIFT_DpT0_EE4typeEEOSF_DpOSG_EUlvE_E9_M_invokeERKSt9_Any_data
    @     0x5638fe35c634  colmap::ThreadPool::WorkerFunc()
    @     0x7f5e00fcd793  (unknown)
    @     0x7f5e01401609  start_thread
    @     0x7f5e00c4d353  clone
    @              (nil)  (unknown)
[1]    3803722 abort (core dumped)  colmap GUI
```

**Comment by paidiakileswar** [comment]
@satyajitghana 

As My aim is to get best sparse -> I was running till the SFM stage only

Like 
Till -> colmap mapper 

I am not much aware of why this error occured in the MVS stage

**Comment by paidiakileswar** [comment]
@satyajitghana Any info about about your try ??

**Comment by json87** [comment]
Hi, all. This repo only implements SfM for spherical images.

**Comment by paidiakileswar** [comment]
> Hai @json87 @satyajitghana
> 
> I was trying to merge my 2 models
> 
> ## **Method - 1:**
> So Firstly i divided my images
> 
> SPLIT 1 => 1- 400 SPLIT 2 => 300 - 700
> 
> Here i got 2 sparses as output from both SPLIT 1 and SPLIT 2 , Both of them i reconstucted in differently , (like in 2 servers )
> 
> So i have now scaled outputs of SPLIT 1 & SPLIT 2 which i have got after applying mapper & model aligner
> 
> Now I have 2 sparses i converted them into .txt files
> 
> So i have sparse_1 -> cameras.txt,images.txt,points3D.txt
> 
> sparse_2 -> cameras.txt,images.txt,points3D.txt
> 
> I have modified the image_id in both images.txt & points3D.txt , such that they are unique as per [colmap/colmap#1703 (comment)](https://github.com/colmap/colmap/issues/1703#issuecomment-1331828759)
> 
> ![Screenshot 2024-06-25 142533](https://private-user-images.githubusercontent.com/155959310/342682175-d9924cee-b6cf-45dc-a3d5-e95814b7a07d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MTUxOTEsIm5iZiI6MTcyMDQxNDg5MSwicGF0aCI6Ii8xNTU5NTkzMTAvMzQyNjgyMTc1LWQ5OTI0Y2VlLWI2Y2YtNDVkYy1hM2Q1LWU5NTgxNGI3YTA3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwNTAxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWFlNzc2OGJmY2Y0YmI1YWY0ODY5NWQzNWM5OGMyZTY1MjdmZjBmYWY1ZjA4YWFlZDlkYTU5YjQ5NDNhZmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tr0Lle7ShC-347kIyTEmvuNq2j6mjTyhd19EQcsYCVQ)
> 
> I am getting this issue , Please help me here
> 
> ## **Method - 2:**
> Here i have 438 images
> 
> I divided as 1 - 250 200 - 438
> 
> So i done Feature Extraction , Matching ,
> 
> Mapper here i changed the using --image_list_path names_1.txt --image_list_path names_2.txt
> 
> I got 2 sparses
> 
> While merging `colmap model_merger --input_path1 ./sparse/0/ --input_path2 ./sparse_1/0/ --output_path ./merger/ `
> 
> I got this issue
> 
> ![image](https://private-user-images.githubusercontent.com/155959310/342695866-839ad4e7-8a3d-46a1-9982-f5ea80d14549.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MTUxOTEsIm5iZiI6MTcyMDQxNDg5MSwicGF0aCI6Ii8xNTU5NTkzMTAvMzQyNjk1ODY2LTgzOWFkNGU3LThhM2QtNDZhMS05OTgyLWY1ZWE4MGQxNDU0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwNTAxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDhhM2U0NmNlMjU5YzgyZGEyYmNlYWI2ZjA4MTM2MzY3YmNiOWYwNDg4NWNhNzRjZjkxNjYzYmE0NDliNmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1UmOIOpxIa3oQnI-vlDFYbZvRFZefjn53M1YCw5aC9M)
> 
> Stack Backtrace
> 
> ![image](https://private-user-images.githubusercontent.com/155959310/342700071-a18a5d98-bf84-470e-b4c2-52cc3788eebd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MTUxOTEsIm5iZiI6MTcyMDQxNDg5MSwicGF0aCI6Ii8xNTU5NTkzMTAvMzQyNzAwMDcxLWExOGE1ZDk4LWJmODQtNDcwZS1iNGMyLTUyY2MzNzg4ZWViZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwNTAxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMWQxZjRlMWE4YmZlNzMxNWZmODdjZjI3YTYyOWZlMGUzMzE4MzUxYjc0YWM2NzBlYjUxZjdkODVhNGEwYzA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XIb-ASSKuO7-35jZIoi_joJCuasVZdZKOMnd4nmX_GI)
> 
> Could you help me here , I am stuck here Best Regards Akil

Can you help with this !! This is my main issue > @json87

**Comment by json87** [comment]
I have not test model merge for spherical images, If possible, you can share these two models for test.
