### ISSUE TITLE
Fail to get dense reconstruction result

### ISSUE THREAD

**Issue by FengyuGuo** [json87/SphereSfM#21]
sparse reconstruction success on dataset recorded by my insta360 device. but failed to get dense reconstruction result.

one of the depth is like below

![Screenshot from 2024-07-08 10-02-16](https://github.com/json87/SphereSfM/assets/10389422/3d8f2cbe-5740-446c-851c-945e0b0fbb7f)

**Comment by json87** [comment]
The current version only implements SfM for spherical images.

**Comment by FengyuGuo** [comment]
so the dense reconstruction in the paper is not open sourced yet?

**Comment by json87** [comment]
The dense matching is achieved by converting the spherical SFM results into perspective SFM results. In details, it converts each spherical images into six pinhole images in the cubic-map format.

**Comment by FengyuGuo** [comment]
that sounds easy to implement through just few line of python scripts. thanks!
