### ISSUE TITLE
Mapping with multiple camera models supported in SphereSfM?

### ISSUE THREAD

**Issue by Byson-source** [json87/SphereSfM#29]
Hello, thank you for your excellent work!!

I have a question. I assume the original COLMAP can involve different camera intrinsic (models) in its reconstruction process.
Regarding SphereSfM, one mapper option settles whether the sphere camera is used (—-Mapper.sphere_camera).

Does this option allow SphereSfm to involve different camera models besides Sphere cameras? 
If not, how can I do this?

**Comment by json87** [comment]
In current version, SphereSfM cannot process images with spherical and other camera models.

**Comment by Byson-source** [comment]
I got it! Thanks for your reply!
