### ISSUE TITLE
hierarchical_mapper raised an error during the final Merge

### ISSUE THREAD

**Issue by lingkun93** [json87/SphereSfM#30]
Merging clusters
==============================================================================

terminate called after throwing an instance of 'std::out_of_range'
what():  _Map_base::at
*** Aborted at 1734502084 (unix time) try "date -d @1734502084" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x7fa819af2b3e) received by PID 3058 (TID 0x7fa7ec9ff000) from PID 430910270; stack trace: ***
@     0x7fa833ca4046 (unknown)
@     0x7fa81986a520 (unknown)
@     0x7fa8198be9fc pthread_kill
@     0x7fa81986a476 raise
@     0x7fa8198507f3 abort
@     0x7fa819af2b9e (unknown)
@     0x7fa819afe20c (unknown)
@     0x7fa819afe277 std::terminate()
@     0x7fa819afe4d8 __cxa_throw
@     0x7fa819af54a0 std::__throw_out_of_range()
@     0x5590cd7df34a colmap::Reconstruction::Merge()
@     0x5590cd81687d colmap::(anonymous namespace)::MergeClusters()
@     0x5590cd817f0b colmap::HierarchicalMapperController::Run()
@     0x5590cd9a9386 colmap::Thread::RunFunc()
@     0x7fa819b2c253 (unknown)
@     0x7fa8198bcac3 (unknown)
@     0x7fa81994dbf4 clone

**Comment by lingkun93** [comment]
我试跑了hierarchical_mapper，开了snapshot保存，分块的每个子地图都成功了，最后MergeClusters中Reconstruction::Merge(const Reconstruction& reconstruction,  const double max_reproj_error)内报索引超出std::out_of_range，没有debug编译，没有细查函数内具体哪一行报错。几次试跑不同数据都报了同样错误

bool Reconstruction::Merge(const Reconstruction& reconstruction,
                           const double max_reproj_error) {
  const double kMinInlierObservations = 0.3;

  Eigen::Matrix3x4d alignment;
  if (!ComputeAlignmentBetweenReconstructions(reconstruction, *this,
                                              kMinInlierObservations,
                                              max_reproj_error, &alignment)) {
    return false;
  }

  const SimilarityTransform3 tform(alignment);

  // Find common and missing images in the two reconstructions.

  std::unordered_set<image_t> common_image_ids;
  common_image_ids.reserve(reconstruction.NumRegImages());
  std::unordered_set<image_t> missing_image_ids;
  missing_image_ids.reserve(reconstruction.NumRegImages());

  for (const auto& image_id : reconstruction.RegImageIds()) {
    if (ExistsImage(image_id)) {
      common_image_ids.insert(image_id);
    } else {
      missing_image_ids.insert(image_id);
    }
  }

  // Register the missing images in this reconstruction.

  for (const auto image_id : missing_image_ids) {
    auto reg_image = reconstruction.Image(image_id);
    reg_image.SetRegistered(false);
    AddImage(reg_image);
    RegisterImage(image_id);
    if (!ExistsCamera(reg_image.CameraId())) {
      AddCamera(reconstruction.Camera(reg_image.CameraId()));
    }
    auto& image = Image(image_id);
    tform.TransformPose(&image.Qvec(), &image.Tvec());
  }

  // Merge the two point clouds using the following two rules:
  //    - copy points to this reconstruction with non-conflicting tracks,
  //      i.e. points that do not have an already triangulated observation
  //      in this reconstruction.
  //    - merge tracks that are unambiguous, i.e. only merge points in the two
  //      reconstructions if they have a one-to-one mapping.
  // Note that in both cases no cheirality or reprojection test is performed.

  for (const auto& point3D : reconstruction.Points3D()) {
    Track new_track;
    Track old_track;
    std::unordered_set<point3D_t> old_point3D_ids;
    for (const auto& track_el : point3D.second.Track().Elements()) {
      if (common_image_ids.count(track_el.image_id) > 0) {
        const auto& point2D =
            Image(track_el.image_id).Point2D(track_el.point2D_idx);
        if (point2D.HasPoint3D()) {
          old_track.AddElement(track_el);
          old_point3D_ids.insert(point2D.Point3DId());
        } else {
          new_track.AddElement(track_el);
        }
      } else if (missing_image_ids.count(track_el.image_id) > 0) {
        Image(track_el.image_id).ResetPoint3DForPoint2D(track_el.point2D_idx);
        new_track.AddElement(track_el);
      }
    }

    const bool create_new_point = new_track.Length() >= 2;
    const bool merge_new_and_old_point =
        (new_track.Length() + old_track.Length()) >= 2 &&
        old_point3D_ids.size() == 1;
    if (create_new_point || merge_new_and_old_point) {
      Eigen::Vector3d xyz = point3D.second.XYZ();
      tform.TransformPoint(&xyz);
      const auto point3D_id =
          AddPoint3D(xyz, new_track, point3D.second.Color());
      if (old_point3D_ids.size() == 1) {
        MergePoints3D(point3D_id, *old_point3D_ids.begin());
      }
    }
  }

  FilterPoints3DWithLargeReprojectionError(max_reproj_error, Point3DIds());
}

**Comment by json87** [comment]
Can you share the dataset with me for testing?

**Comment by lingkun93** [comment]
sorry the data is restricted, I've decided not to use the hierarchical mapper, regardless of this issue. however this issue may exist in most datasets including opensource. thanks.
