### ISSUE TITLE
Issue While opening Sparse Output that we got from SphereSfm in Colmap GUI

### ISSUE THREAD

**Issue by paidiakileswar** [json87/SphereSfM#4]
After Running of mapper we will get a sparse ! There I got two Sparses 

**1st Sparse**

```
0
--> cameras.bin
--> images.bin
--> points3D.bin
--> project.ini
```

**2nd Sparse**

```
1
--> cameras.bin
--> images.bin
--> points3D.bin
--> project.ini
```

So While i am importing the model From colmap GUI
![image](https://github.com/json87/SphereSfM/assets/155959310/56cdda31-6392-46df-a8c5-c0360f24ea95)

It is going back and getting closed Total UI! I tried many times But it is not opened

**Questions:**
1) Here  How can view the sparse reconstruction? Should I use UI Setup by you?
2) If I should use your UI , Can i know how to install that UI in my local system (Windows) , Can You provide me with colmap.bat file like the one provided by Colmap !
3) Could you provide how can we view Sparse that we got output ! In Windows(Priorityly) and Ubuntu

**Comment by json87** [comment]
Yes, you should use the UI from the ColMap built from this repo.  You can open the UI by justing typying the following cmd in the commond-line-window

colmap gui

**Comment by paidiakileswar** [comment]
Actually I have already Setup and Build this Repo and Environment in GCP Linux Server , Can i know how can i proceed now ! 

Any other way (or) Should I Build whole setup in windows for sure to view the UI from this repo !

**Comment by json87** [comment]
I do not use the GCP Linux Server. Actually, the GUI can be used in both Windows and Linux systems. Maybe I can provide a pre-built release version of this exe.

Best regards.

**Comment by paidiakileswar** [comment]
Okay , Good to hear that ,
Can I have pre-built exe file for windows !

**Comment by json87** [comment]
I have released the pre-built version for Windows in the repo.

FYI.

**Comment by paidiakileswar** [comment]
Okay Thanks ! Can i know how to install it (or) open SphereSfm ui

![image](https://github.com/json87/SphereSfM/assets/155959310/2355f0de-9d00-4378-aa61-423a89544756)

I am trying to open colmap.exe It is opening a terminal and closing automatically

**Comment by paidiakileswar** [comment]
I installed the SphereSfm zip file attached in releases :) 

I extracted them I have a bin folder and 

- Files with .dll extension
- Files with .exe extension
- Platforms folder

How to open UI , Can i know please ! 
As i got sparse output but i cant view them !! 

Please help me with this !!

**Comment by paidiakileswar** [comment]
Hello ! Can you tell me 
Solution for above query !!

**Comment by ZhongmiaoYan** [comment]
> I have released the pre-built version for Windows in the repo.
> 
> FYI.

Hello, thanks for sharing your great work. Where can I find pre-built exe file for windows ? I can't find it in this repo.
I can build this project in my Ubuntu system. But a pre-built exe file for windows will be more convention for me.
I can run the original Colmap GUI by clicking the COLMAP.bat in my Windows system. So I also tried to click the colmap.bat in the ./scripts/shell to run the SphereColmap GUI. But I failed.

**Comment by json87** [comment]
The pre-built exe files can be accessed on the right side of the main repo page. To open the GUI, you can use the colmap gui command in the command-line window.

**Comment by ZhongmiaoYan** [comment]
Thanks for your reply! I have found the exe file and successfully ran the GUI interface. I successfully tested it on my dataset of equirectangular images.
![未命名1713853117](https://github.com/json87/SphereSfM/assets/103210661/1af49dcf-77ad-4f4d-b8cf-6929f129a71e)
I would like to share my experience by the way. I am already able to successfully run the original colmap GUI on my Windows. So I tried to run the colmap.exe or use the command "start colmap.exe gui" directly, but failed. Then I copied the COLMAP.bat file from the original COLMAP to the directory  "./SphereSfM/". After that, I clicked COLMAP.bat and successfully ran the GUI of SphereSfM.
![未命名1713854064](https://github.com/json87/SphereSfM/assets/103210661/733441c8-84aa-4e4f-9fa1-2611dad598d1)

**Comment by json87** [comment]
> Thanks for your reply! I have found the exe file and successfully ran the GUI interface. I successfully tested it on my dataset of equirectangular images.
> 
> ![未命名1713853117](https://private-user-images.githubusercontent.com/103210661/324716333-1af49dcf-77ad-4f4d-b8cf-6929f129a71e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTcxNzgsIm5iZiI6MTcxNDA1Njg3OCwicGF0aCI6Ii8xMDMyMTA2NjEvMzI0NzE2MzMzLTFhZjQ5ZGNmLTc3YWQtNGY0ZC1iOGNmLTY5MjlmMTI5YTcxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxNDU0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzFmNGQ2M2U5ZDRkZDRlZjk5YzBjZDczNjM1ZGU4N2QwNTBiYzBlZGQ4MzQ3MWUyYzk1MDAxMGZmMGZhY2I2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LO5GMMrTCF-u7Ervqngb76r8W6CyVsLTwjdcpTilUik)
> 
> I would like to share my experience by the way. I am already able to successfully run the original colmap GUI on my Windows. So I tried to run the colmap.exe or use the command "start colmap.exe gui" directly, but failed. Then I copied the COLMAP.bat file from the original COLMAP to the directory "./SphereSfM/". After that, I clicked COLMAP.bat and successfully ran the GUI of SphereSfM.
> 
> ![未命名1713854064](https://private-user-images.githubusercontent.com/103210661/324720499-733441c8-84aa-4e4f-9fa1-2611dad598d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTcxNzgsIm5iZiI6MTcxNDA1Njg3OCwicGF0aCI6Ii8xMDMyMTA2NjEvMzI0NzIwNDk5LTczMzQ0MWM4LTg0YWEtNGU0Zi05ZmExLTI2MTFkYWQ1OThkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxNDU0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTM3OGY0NjY0YmNjYWM5MTg0OTlhMzc4ZWEzNzY4MmY3ZjM3MWZkZWFhZGM5MDIzMzc4M2U5MGNmYzVhNDk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.msuK5aXVpg-TE9YwCf7ujuEDXneBXzCfGDiRrceD1IU)

Glad to hear the successful running.
