### ISSUE TITLE
Access to the Datasets mentioned in Repo

### ISSUE THREAD

**Issue by paidiakileswar** [json87/SphereSfM#5]
Hello ,

As my setup and environment is done ! I want to test now with help of different datasets ! So could you please provide me access to the 3 datasets provided in repo !!

**Datasets** :
- Campus Parterre
- Campus Building
- Urban street

Please provide google drive access as we cannot access baidu here !!

Once i got clear from UI i can visualise the outputs directly in sphereSfm UI

**Comment by paidiakileswar** [comment]
![image](https://github.com/json87/SphereSfM/assets/155959310/563fbeb9-1641-405f-a299-caf957a7e924)

Still it is showing access denied ! Can you check that ??

**Comment by json87** [comment]
Sorry. I have forgot to modify the access authority. You can try again.

**Comment by paidiakileswar** [comment]
Yes now I got access to google drive of all projects !!

Thanks a Lot Bro !!
