### ISSUE TITLE
Issue Regarding Sparse Reconstruction

### ISSUE THREAD

**Issue by paidiakileswar** [json87/SphereSfM#6]
Hai ,

# Issue is : While trying on my dataset which is 360 Deg images, The output Sparse is not reconstructing well.

## **Image Specifications:**
Camera : Insta360 ONE X2
Dataset : Phoenix
Image type : JPEG
Image size : 4096 * 2048
Image size in mb : 1.5 to 2 mb

## Dataset Details
Dataset Phoenix : 303 Images 
Sample Dataset image :
![VID_20230926_154316_10_041_IMG_00216_JPG rf fb0fd8aaa396ed5afef3bd6196fa8d97](https://github.com/json87/SphereSfM/assets/155959310/7f291166-b9ce-40c7-99da-1c437f31b877)

## Output Reconstruction: (While trying Vocab Tree Matching , Exhaustive Matching without POS.txt=> Output Sparse size formed is 8.2 MB )
![image](https://github.com/json87/SphereSfM/assets/155959310/ddad235e-a67f-4c7c-bfda-48c8a0d885c4)

Please , Can i know How can we improve this 
1) Are there are any specific things to be considered when the running of SphereSfm , Please mention them , 
2) Can i know what things did you considered here in the dataset (Like camera side and other )

Thanks ! Hope reply from you ,..

**Comment by json87** [comment]
You should share the used command lines first. The main difference is the camera parameter setting from the command line listed in this repo README.

**Comment by paidiakileswar** [comment]
Okay my command are :
# 1
colmap database_creator --database_path ./colmap/database.db

# 2
time colmap feature_extractor \
    --database_path ./colmap/database.db \
    --image_path ./images \
    --ImageReader.camera_model SPHERE \
    --ImageReader.camera_params "1,2048,1024" \
    --ImageReader.single_camera 1 \
    --ImageReader.pose_path ./POS.txt

# 3
time colmap spatial_matcher \
    --database_path ./colmap/database.db \
    --SiftMatching.max_error 4 \
    --SiftMatching.min_num_inliers 50 \
    --SpatialMatching.is_gps 0 \
    --SpatialMatching.max_distance 50

# 4 
time colmap mapper \
    --database_path ./colmap/database.db \
    --image_path ./images \
    --output_path ./colmap/sparse \
    --Mapper.ba_refine_focal_length 0 \
    --Mapper.ba_refine_principal_point 0 \
    --Mapper.ba_refine_extra_params 0 \
    --Mapper.sphere_camera 1 \


These are my parameters !!

Hope this helps you to answer my query !

**Comment by json87** [comment]
I cannot find the issue from the commands. The most possible reason maybe the overlap degree of recorded images.

If possible, you can share your dataset for test.

**Comment by paidiakileswar** [comment]
Haii @json87 ,

So Is there a way to tweak parameters at each stage So I get good results for my failed cases !
Like,
```
Feature Extraction
Feature Matching
Mapper 
```

Eg : Increasing features or make some changes in some parameters , Will it may enhance my sparse Reconstruction 
As i am getting very poor sparse reconstruction to my data ! (or) What parameters that tweaked and considered by you are only the best ??

![image](https://github.com/json87/SphereSfM/assets/155959310/3d5ba6da-9b91-46ea-b9ac-279a0b6a5c60)

Thanks , Hoping a good reply !

**Comment by json87** [comment]
For indoor scenes, I think the feature matching step is the key issue since there are not enough matches can be found or there are too many false matches in these scenes.

**Comment by paidiakileswar** [comment]
Okay @json87 

This dataset is actually indoor dataset like a floor in building , So I tried like Spatial,Sequential,Exhaustive too , In all cases the SphereSfm is failing ! I tried to tweak parameters still no improvement !

So
1) Can i know what may be a reason why it may failing !
2) Can we improve anyway any suggestion , to make improvement
3) or This SphereSfm works good for only outdoor scenes well ,than compared to indoor scenes with more objects ??

Hope these answers will help me !!

**Comment by json87** [comment]
You could consider using learned features or matching methods instead of SIFT.

**Comment by paidiakileswar** [comment]
Hai @json87 

So My dataset is of full dark places and contains full of white walls where usually there is no features at that place but still there will some features like doors and some other objects ! 

So in this case i considered number of features to 100,000 and considering SIFT disp and changed some params !! Even though spatial,Exhaustive,Sequential Matching failed here !!

When considering maximum resolution 6720*3360 , Even though features and matches got increased the reconstruction is not forming well !!

So please can you suggest me some ideas or suggestions how can i finally sparse in these cases??
