### ISSUE TITLE
Clarification Needed on Source and Calculation of Rotation Array in POS.txt

### ISSUE THREAD

**Issue by zhangChen341** [json87/SphereSfM#7]
Hello,

I'm working with coordinate data (POS.txt ) that includes spatial positions and a rotation array, as outlined in the following format: #F=N X Y Z R 
An example entry from the data is as follows:

**Example For an image in POS.txt :**
`
Job_202306201252_Track01_Sphere_00001.jpg 182.0801976 536.9640277 5.533966177 0.979997362 -0.011776529 0.198661731 0.19834921 -0.023510662 -0.979849396 0.016209893 0.999654221 -0.020704522`

How can I get :
`R = [0.979997362 -0.011776529 0.198661731 0.19834921 -0.023510662 -0.979849396 0.016209893 0.999654221 -0.020704522 ]`

Please Can i Know,

- **Calculation of Rotation Array:** How is the rotation array derived? 
- **Source of Rotation Data:** Is the rotation array directly measured from metadata , or is it computed? If it is computed, could you provide details on the source data and computation methods?
- Any documentation, references, or examples related to the rotation array would be greatly appreciated. 

Thank you for your assistance!

Best regards,
Zhang

**Comment by json87** [comment]
You can refer to the paper listed in the repo page "3D reconstruction of spherical images based on incremental structure from motion".  The ground-truth data is captured by using on-board high-precision POS system of the MMS.

**Comment by zhangChen341** [comment]
My dataset is took from Insta360 X2 camera ,

How can i have the rotation data , Will there a seperate system to capture spatial rotations of each frame , I have x,y,z with me but i am not able to get rotations to keep in Pos.txt 

Can you help me with that ?

or

Any guide to get them and use them in our dataset ! As the spatial gives good results compared to Exhaustive & Vocab tree

**Comment by json87** [comment]
> My dataset is took from Insta360 X2 camera ,
> 
> How can i have the rotation data , Will there a seperate system to capture spatial rotations of each frame , I have x,y,z with me but i am not able to get rotations to keep in Pos.txt
> 
> Can you help me with that ?
> 
> or
> 
> Any guide to get them and use them in our dataset ! As the spatial gives good results compared to Exhaustive & Vocab tree

For feature matching, XYZ is enough as the angles are not used in the spatial matching algorithm.  Thus, you can define R as an identity matrix in the POS.txt

**Comment by zhangChen341** [comment]
Okay ! But still I am loosing some poses !
