### ISSUE TITLE
ImageReader.pose_path is not recognised

### ISSUE THREAD

**Issue by Anirudh-Kakarlapudi** [json87/SphereSfM#8]
Hi @json87 

Thanks for the amazing work.

1) I successfully built the COLMAP within this repo (cuda version) on Ubuntu 22.04 system.

2) Then I ran the following command for a dataset
```
colmap feature_extractor \
--database_path ./colmap/database.db \
--image_path ./images \
--ImageReader.camera_model SPHERE \
--ImageReader.camera_params "1,4096,2048" \
--ImageReader.single_camera 1 \
--ImageReader.pose_path ./POS.txt
```

3) I have encountered the following error. 
![Screenshot from 2024-05-02 20-02-56](https://github.com/json87/SphereSfM/assets/43009364/01d71476-8d50-457b-8e46-748ebd3667c6)

Where did I go wrong? Is there something I am missing? Any suggestions would be of great help. 

Note: The POS.txt has image name, x,y,z and identity matrix as rotations.

**Comment by Mete-cell** [comment]
How did you built the repo? I built it on Ubuntu 22.04 but there is no sphere camera model available. Neither in the gui nor in the console.

**Comment by json87** [comment]
> Hi @json87
> 
> Thanks for the amazing work.
> 
>     1. I successfully built the COLMAP within this repo (cuda version) on Ubuntu 22.04 system.
> 
>     2. Then I ran the following command for a dataset
> 
> 
> ```
> colmap feature_extractor \
> --database_path ./colmap/database.db \
> --image_path ./images \
> --ImageReader.camera_model SPHERE \
> --ImageReader.camera_params "1,4096,2048" \
> --ImageReader.single_camera 1 \
> --ImageReader.pose_path ./POS.txt
> ```
> 
>     3. I have encountered the following error.
>        ![Screenshot from 2024-05-02 20-02-56](https://private-user-images.githubusercontent.com/43009364/327470710-01d71476-8d50-457b-8e46-748ebd3667c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3ODAwMjQsIm5iZiI6MTcxNDc3OTcyNCwicGF0aCI6Ii80MzAwOTM2NC8zMjc0NzA3MTAtMDFkNzE0NzYtOGQ1MC00NTdiLThlNDYtNzQ4ZWJkMzY2N2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDIzNDIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MzI2NWZjNWUwY2JkNzMzM2M3ODMzMTZjNzAwOTgxMDkyODg3OTI0MjZkNTNiZWVkY2NmZDNkMGMwMzQ1OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s1LQhG2A7qqxeIzkJhG08nyDart5ecZD8RUVDZNFyfc)
> 
> 
> Where did I go wrong? Is there something I am missing? Any suggestions would be of great help.
> 
> Note: The POS.txt has image name, x,y,z and identity matrix as rotations.

I think you should distinguish capitals from lower case letters.
