### ISSUE TITLE
Dense matching

### ISSUE THREAD

**Issue by arihaz** [json87/SphereSfM#9]
Hello ! Thanks for this great work ! 
Referring to your paper, I saw that you performed dense matching by converting the _mapper_ results to a cubic-map representation. Did you also release the code to perform this conversion / create the corresponding cube maps and continue the reconstruction pipeline ?

Thanks again !

**Comment by json87** [comment]
The code for cubic-map conversion is not released in this repo. I would consider releasing this function latter.
